### ISSUE TITLE
error install

### ISSUE THREAD

**Issue by laipham** [pgrabowski/mediactrl#1]
Hi all,
I try to configure file but fail. I totally install reSIProcate but cannot install lib ares. Let check reSIProcate and i don't find anything about lib ares,
I run ./configure and i got 
"checking for ares_init in -lares... no
configure: error: Please install libares (reSIProcate)
"
Maybe i can use c-ares to replace libares. Plz help me

**Comment by pgrabowski** [comment]
HI,
Are you using latest version in GIT?
In last version I have changed configure.in to use c-ares:
`AC_CHECK_LIB(cares, ares_init, , AC_MSG_ERROR([Please install libares (reSIProcate)]))`
Also in docker folder you have a Debian based container that can be used to compile project.

**Comment by laipham** [comment]
I edit file configure in line 19439 and 19499 replace libares become libcares, but so painful to install library because the lastest verison of reSIProcate and openssl and boost are not support. Could you give me the version of these library. Thanks

**Comment by pgrabowski** [comment]
libresiprocate-1.11 (1:1.11.0~beta1-3)
libboost-all-dev (1.62.0.1)
libssl1.0-dev (1.0.2l-2)

as in previous comment project builds on Debian 9
